name: CI

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Prepare ARM host
        run: ssh-keyscan ${{ secrets.DOCKER_ARM_HOST }} >> ~/.ssh/known_hosts

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Add arm64 builder
        run: |
          docker buildx create --append --name ${{ steps.buildx.outputs.name }} ssh://root@${{ secrets.DOCKER_ARM_HOST }}
          docker buildx inspect --bootstrap ${{ steps.buildx.outputs.name }}

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          cache-from: '"silex/nix:latest"'
          cache-to: '"type=inline"'
          tags: '"silex/nix:latest"'
          context: .
